/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalReviewsRouteImport } from './routes/_authenticated/portal.reviews'
import { Route as AuthenticatedPortalProjectsRouteImport } from './routes/_authenticated/portal.projects'
import { Route as AuthenticatedPortalMessagesRouteImport } from './routes/_authenticated/portal.messages'
import { Route as AuthenticatedPortalInvoicesRouteImport } from './routes/_authenticated/portal.invoices'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalReviewsRoute =
  AuthenticatedPortalReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProjectsRoute =
  AuthenticatedPortalProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMessagesRoute =
  AuthenticatedPortalMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalInvoicesRoute =
  AuthenticatedPortalInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/projects': typeof AuthenticatedPortalProjectsRoute
  '/portal/reviews': typeof AuthenticatedPortalReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/projects': typeof AuthenticatedPortalProjectsRoute
  '/portal/reviews': typeof AuthenticatedPortalReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/_authenticated/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/_authenticated/portal/projects': typeof AuthenticatedPortalProjectsRoute
  '/_authenticated/portal/reviews': typeof AuthenticatedPortalReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/portfolio'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/vision'
    | '/admin'
    | '/portal'
    | '/admin/clients'
    | '/admin/contact'
    | '/admin/projects'
    | '/admin/reviews'
    | '/portal/invoices'
    | '/portal/messages'
    | '/portal/projects'
    | '/portal/reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/portfolio'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/vision'
    | '/admin'
    | '/portal'
    | '/admin/clients'
    | '/admin/contact'
    | '/admin/projects'
    | '/admin/reviews'
    | '/portal/invoices'
    | '/portal/messages'
    | '/portal/projects'
    | '/portal/reviews'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/portfolio'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/vision'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/portal/invoices'
    | '/_authenticated/portal/messages'
    | '/_authenticated/portal/projects'
    | '/_authenticated/portal/reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AwardsRoute: typeof AwardsRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PortfolioRoute: typeof PortfolioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/reviews': {
      id: '/_authenticated/portal/reviews'
      path: '/reviews'
      fullPath: '/portal/reviews'
      preLoaderRoute: typeof AuthenticatedPortalReviewsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/projects': {
      id: '/_authenticated/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof AuthenticatedPortalProjectsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/messages': {
      id: '/_authenticated/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof AuthenticatedPortalMessagesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/invoices': {
      id: '/_authenticated/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof AuthenticatedPortalInvoicesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalInvoicesRoute: typeof AuthenticatedPortalInvoicesRoute
  AuthenticatedPortalMessagesRoute: typeof AuthenticatedPortalMessagesRoute
  AuthenticatedPortalProjectsRoute: typeof AuthenticatedPortalProjectsRoute
  AuthenticatedPortalReviewsRoute: typeof AuthenticatedPortalReviewsRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalInvoicesRoute: AuthenticatedPortalInvoicesRoute,
  AuthenticatedPortalMessagesRoute: AuthenticatedPortalMessagesRoute,
  AuthenticatedPortalProjectsRoute: AuthenticatedPortalProjectsRoute,
  AuthenticatedPortalReviewsRoute: AuthenticatedPortalReviewsRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AwardsRoute: AwardsRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PortfolioRoute: PortfolioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
