/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as LabsSwiftdropRouteImport } from './routes/labs.swiftdrop'
import { Route as LabsNdingubaniTvRouteImport } from './routes/labs.ndingubani-tv'
import { Route as LabsCvBuilderRouteImport } from './routes/labs.cv-builder'
import { Route as LabsCivicFacenetRouteImport } from './routes/labs.civic-facenet'
import { Route as LabsCalculatorRouteImport } from './routes/labs.calculator'
import { Route as LabsBarStockRouteImport } from './routes/labs.bar-stock'
import { Route as LabsAmdBotRouteImport } from './routes/labs.amd-bot'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AuthenticatedPortalReviewsRouteImport } from './routes/_authenticated/portal.reviews'
import { Route as AuthenticatedPortalProjectsRouteImport } from './routes/_authenticated/portal.projects'
import { Route as AuthenticatedPortalMessagesRouteImport } from './routes/_authenticated/portal.messages'
import { Route as AuthenticatedPortalInvoicesRouteImport } from './routes/_authenticated/portal.invoices'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsSwiftdropRoute = LabsSwiftdropRouteImport.update({
  id: '/labs/swiftdrop',
  path: '/labs/swiftdrop',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsNdingubaniTvRoute = LabsNdingubaniTvRouteImport.update({
  id: '/labs/ndingubani-tv',
  path: '/labs/ndingubani-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsCvBuilderRoute = LabsCvBuilderRouteImport.update({
  id: '/labs/cv-builder',
  path: '/labs/cv-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsCivicFacenetRoute = LabsCivicFacenetRouteImport.update({
  id: '/labs/civic-facenet',
  path: '/labs/civic-facenet',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsCalculatorRoute = LabsCalculatorRouteImport.update({
  id: '/labs/calculator',
  path: '/labs/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsBarStockRoute = LabsBarStockRouteImport.update({
  id: '/labs/bar-stock',
  path: '/labs/bar-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsAmdBotRoute = LabsAmdBotRouteImport.update({
  id: '/labs/amd-bot',
  path: '/labs/amd-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalReviewsRoute =
  AuthenticatedPortalReviewsRouteImport.update({
    id: '/portal/reviews',
    path: '/portal/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalProjectsRoute =
  AuthenticatedPortalProjectsRouteImport.update({
    id: '/portal/projects',
    path: '/portal/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalMessagesRoute =
  AuthenticatedPortalMessagesRouteImport.update({
    id: '/portal/messages',
    path: '/portal/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalInvoicesRoute =
  AuthenticatedPortalInvoicesRouteImport.update({
    id: '/portal/invoices',
    path: '/portal/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/admin/reviews',
    path: '/admin/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/admin/projects',
    path: '/admin/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/admin/contact',
    path: '/admin/contact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/admin/clients',
    path: '/admin/clients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/labs/amd-bot': typeof LabsAmdBotRoute
  '/labs/bar-stock': typeof LabsBarStockRoute
  '/labs/calculator': typeof LabsCalculatorRoute
  '/labs/civic-facenet': typeof LabsCivicFacenetRoute
  '/labs/cv-builder': typeof LabsCvBuilderRoute
  '/labs/ndingubani-tv': typeof LabsNdingubaniTvRoute
  '/labs/swiftdrop': typeof LabsSwiftdropRoute
  '/labs/': typeof LabsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/projects': typeof AuthenticatedPortalProjectsRoute
  '/portal/reviews': typeof AuthenticatedPortalReviewsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/labs/amd-bot': typeof LabsAmdBotRoute
  '/labs/bar-stock': typeof LabsBarStockRoute
  '/labs/calculator': typeof LabsCalculatorRoute
  '/labs/civic-facenet': typeof LabsCivicFacenetRoute
  '/labs/cv-builder': typeof LabsCvBuilderRoute
  '/labs/ndingubani-tv': typeof LabsNdingubaniTvRoute
  '/labs/swiftdrop': typeof LabsSwiftdropRoute
  '/labs': typeof LabsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/projects': typeof AuthenticatedPortalProjectsRoute
  '/portal/reviews': typeof AuthenticatedPortalReviewsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/vision': typeof VisionRoute
  '/labs/amd-bot': typeof LabsAmdBotRoute
  '/labs/bar-stock': typeof LabsBarStockRoute
  '/labs/calculator': typeof LabsCalculatorRoute
  '/labs/civic-facenet': typeof LabsCivicFacenetRoute
  '/labs/cv-builder': typeof LabsCvBuilderRoute
  '/labs/ndingubani-tv': typeof LabsNdingubaniTvRoute
  '/labs/swiftdrop': typeof LabsSwiftdropRoute
  '/labs/': typeof LabsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/_authenticated/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/_authenticated/portal/projects': typeof AuthenticatedPortalProjectsRoute
  '/_authenticated/portal/reviews': typeof AuthenticatedPortalReviewsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/portfolio'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/vision'
    | '/labs/amd-bot'
    | '/labs/bar-stock'
    | '/labs/calculator'
    | '/labs/civic-facenet'
    | '/labs/cv-builder'
    | '/labs/ndingubani-tv'
    | '/labs/swiftdrop'
    | '/labs/'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/contact'
    | '/admin/projects'
    | '/admin/reviews'
    | '/portal/invoices'
    | '/portal/messages'
    | '/portal/projects'
    | '/portal/reviews'
    | '/api/public/track'
    | '/admin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/portfolio'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/vision'
    | '/labs/amd-bot'
    | '/labs/bar-stock'
    | '/labs/calculator'
    | '/labs/civic-facenet'
    | '/labs/cv-builder'
    | '/labs/ndingubani-tv'
    | '/labs/swiftdrop'
    | '/labs'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/contact'
    | '/admin/projects'
    | '/admin/reviews'
    | '/portal/invoices'
    | '/portal/messages'
    | '/portal/projects'
    | '/portal/reviews'
    | '/api/public/track'
    | '/admin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/portfolio'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/vision'
    | '/labs/amd-bot'
    | '/labs/bar-stock'
    | '/labs/calculator'
    | '/labs/civic-facenet'
    | '/labs/cv-builder'
    | '/labs/ndingubani-tv'
    | '/labs/swiftdrop'
    | '/labs/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/portal/invoices'
    | '/_authenticated/portal/messages'
    | '/_authenticated/portal/projects'
    | '/_authenticated/portal/reviews'
    | '/api/public/track'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AwardsRoute: typeof AwardsRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PortfolioRoute: typeof PortfolioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VisionRoute: typeof VisionRoute
  LabsAmdBotRoute: typeof LabsAmdBotRoute
  LabsBarStockRoute: typeof LabsBarStockRoute
  LabsCalculatorRoute: typeof LabsCalculatorRoute
  LabsCivicFacenetRoute: typeof LabsCivicFacenetRoute
  LabsCvBuilderRoute: typeof LabsCvBuilderRoute
  LabsNdingubaniTvRoute: typeof LabsNdingubaniTvRoute
  LabsSwiftdropRoute: typeof LabsSwiftdropRoute
  LabsIndexRoute: typeof LabsIndexRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/swiftdrop': {
      id: '/labs/swiftdrop'
      path: '/labs/swiftdrop'
      fullPath: '/labs/swiftdrop'
      preLoaderRoute: typeof LabsSwiftdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/ndingubani-tv': {
      id: '/labs/ndingubani-tv'
      path: '/labs/ndingubani-tv'
      fullPath: '/labs/ndingubani-tv'
      preLoaderRoute: typeof LabsNdingubaniTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/cv-builder': {
      id: '/labs/cv-builder'
      path: '/labs/cv-builder'
      fullPath: '/labs/cv-builder'
      preLoaderRoute: typeof LabsCvBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/civic-facenet': {
      id: '/labs/civic-facenet'
      path: '/labs/civic-facenet'
      fullPath: '/labs/civic-facenet'
      preLoaderRoute: typeof LabsCivicFacenetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/calculator': {
      id: '/labs/calculator'
      path: '/labs/calculator'
      fullPath: '/labs/calculator'
      preLoaderRoute: typeof LabsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/bar-stock': {
      id: '/labs/bar-stock'
      path: '/labs/bar-stock'
      fullPath: '/labs/bar-stock'
      preLoaderRoute: typeof LabsBarStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/amd-bot': {
      id: '/labs/amd-bot'
      path: '/labs/amd-bot'
      fullPath: '/labs/amd-bot'
      preLoaderRoute: typeof LabsAmdBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/reviews': {
      id: '/_authenticated/portal/reviews'
      path: '/portal/reviews'
      fullPath: '/portal/reviews'
      preLoaderRoute: typeof AuthenticatedPortalReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/projects': {
      id: '/_authenticated/portal/projects'
      path: '/portal/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof AuthenticatedPortalProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/messages': {
      id: '/_authenticated/portal/messages'
      path: '/portal/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof AuthenticatedPortalMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/invoices': {
      id: '/_authenticated/portal/invoices'
      path: '/portal/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof AuthenticatedPortalInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedPortalInvoicesRoute: typeof AuthenticatedPortalInvoicesRoute
  AuthenticatedPortalMessagesRoute: typeof AuthenticatedPortalMessagesRoute
  AuthenticatedPortalProjectsRoute: typeof AuthenticatedPortalProjectsRoute
  AuthenticatedPortalReviewsRoute: typeof AuthenticatedPortalReviewsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedPortalInvoicesRoute: AuthenticatedPortalInvoicesRoute,
  AuthenticatedPortalMessagesRoute: AuthenticatedPortalMessagesRoute,
  AuthenticatedPortalProjectsRoute: AuthenticatedPortalProjectsRoute,
  AuthenticatedPortalReviewsRoute: AuthenticatedPortalReviewsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AwardsRoute: AwardsRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PortfolioRoute: PortfolioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  VisionRoute: VisionRoute,
  LabsAmdBotRoute: LabsAmdBotRoute,
  LabsBarStockRoute: LabsBarStockRoute,
  LabsCalculatorRoute: LabsCalculatorRoute,
  LabsCivicFacenetRoute: LabsCivicFacenetRoute,
  LabsCvBuilderRoute: LabsCvBuilderRoute,
  LabsNdingubaniTvRoute: LabsNdingubaniTvRoute,
  LabsSwiftdropRoute: LabsSwiftdropRoute,
  LabsIndexRoute: LabsIndexRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
